language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-threejs' ]; then cd .. && eval "mv $currentfolder generator-threejs" && cd generator-threejs; fi
  - npm install -g grunt-cli
